const bar_menu = document.querySelector(".bar_de_menu")
    const menu = document.querySelector(".menu")
    const back = document.querySelector(".back")
    const back1 = document.querySelector(".back1")
    const back2 = document.querySelector(".back2")
    const back3 = document.querySelector(".back3")

    bar_menu.addEventListener('click',()=>{menu.classList.toggle('menu_mobile')
    })
    back.addEventListener('click',()=>{menu.classList.toggle('menu_mobile')
    })
    back1.addEventListener('click',()=>{menu.classList.toggle('menu_mobile')
    })
    back2.addEventListener('click',()=>{menu.classList.toggle('menu_mobile')
    })
    back3.addEventListener('click',()=>{menu.classList.toggle('menu_mobile')
    })